version: '0.15'
services:
    db:
        image: mysql:latest
        environment:
            MYSQL_DATABASE: 'yb'
            MYSQL_USER: 'yb'
            MYSQL_PASSWORD: '1234'
            MYSQL_ROOT_PASSWORD: '1234'
        ports:
            - '3306:3306'
        volumes:
            - '~/yb/docker-volume/mysql:/var/lib/mysql'